(() => {
  const pageDepth = Number.parseInt(document.body?.dataset.depth || "0", 10) || 0;
  const root = new URL("../".repeat(pageDepth), location.href);
  const asset = (path) => new URL(path, root).href;
  const contact = new URL("contact.html", root).href;
  const services = new URL("services.html#all-services", root).href;
  const reviewsUrl = "https://www.google.com/maps/search/?api=1&query=VNW+Media&query_place_id=ChIJH8x-SSDNw4kRL5QM6uUWIV4";

  const reviews = {
    web: [
      ["Ian McWilliams", "VNW Media revamped our pharmaceutical company's website. It now looks modern while still retaining a streamlined and friendly user interface"],
      ["Rob Pennachio", "My company’s website had been down for a few months and was in desperate need of a refresh. I hired VNW for this and they were excellent to work with. The final product is something we can proudly show our clients and easily modify and update as needed down the road."],
      ["Chris Mangano", "Great experience. Vladimir was professional, responsive, easy to communicate with, and really understood the look and feel we were going for. The website came out clean, modern, and easy to navigate. Highly recommend"]
    ],
    seo: [
      ["Gary Tancer", "I have been using these people for a year now and my business is growing by the day. We see the traffic coming into our store almost every day and lots of new local people calling"],
      ["Andrew Mannino", "Since we started working together, my online presence has improved drastically and my company is busier."],
      ["Daniela Krinshpun", "They have an excellent eye for design, are very responsive and were patient with my changes."]
    ],
    marketing: [
      ["Anthony Caputo", "Lily and her team are great. They are constantly working on updating my website as well as working on growing my exposure. Very professional and truly care."],
      ["Yury B", "great experience with web design, launching and optimizing our meta and google campaigns. definitely recommend for any marketing or development needs."],
      ["Michael Feder", "The team understood right away what I needed and delivered an exceptional website very quickly."]
    ],
    ppc: [
      ["Boris Plotinskiy", "Vlad and his team are exceptional. They have been running our advertising for 3 years now and we are extremely happy with the results. They drove a ton of revenue to our company and we are happy to have them as a partner."],
      ["Yury B", "great experience with web design, launching and optimizing our meta and google campaigns. definitely recommend for any marketing or development needs."],
      ["Mark Bratkovsky", "Great company! Always attentive service and results oriented"]
    ]
  };

  const areaFacts = {
    "new-jersey": {
      state: "New Jersey",
      context: "VNW Media is based in Morganville, New Jersey. We work with businesses across the state, building plans around their actual service footprint, audiences, competition, and goals—not a one-size-fits-all city template.",
      places: "Monmouth County, Middlesex County, Ocean County, Mercer County, and communities throughout New Jersey",
      localNote: "Local expertise, direct conversations, and practical market context from a New Jersey-based team.",
      region: "New Jersey"
    },
    "new-york": {
      state: "New York",
      context: "VNW Media partners with New York businesses through a collaborative, remote-first process. We shape each plan around the places a business genuinely serves, its customer journey, and the competitive context of its market.",
      places: "New York City, Brooklyn, Queens, Staten Island, Long Island, and surrounding New York communities where your business operates",
      localNote: "A connected digital partner for New York businesses, with project conversations and collaboration tailored to your team.",
      region: "New York"
    }
  };

  const pages = {
    "digital-marketing-new-jersey": {
      region: "new-jersey", service: "Digital Marketing", image: "nj-digital-marketing.jpg", alt: "Two New Jersey small-business owners reviewing a website together in a welcoming neighborhood shop", proof: "Connected growth planning", reviewSet: "marketing",
      hero: "Digital marketing that helps New Jersey businesses move forward.",
      lead: "Bring your website, search visibility, paid campaigns, and lead follow-up together around a clear business goal.",
      introTitle: "One connected plan for the next customer conversation.",
      intro: "New Jersey businesses often need several digital channels to work together—not a disconnected list of tactics. We start with the audience, offer, service area, and strongest next action, then shape the right combination of website, SEO, paid media, social, and follow-up.",
      cards: [["Start with the customer", "Clarify what people need, what makes your business a fit, and where the decision currently gets stuck."], ["Make the experience clearer", "Align your message, website, service pages, and calls to action so prospects know what to do next."], ["Connect discovery to action", "Coordinate organic search, Google Ads, social campaigns, landing pages, and measurement around the right audience."], ["Learn and improve", "Use meaningful inquiries and campaign signals to guide the next set of decisions." ]],
      systemTitle: "A practical mix of strategy, creative, and performance.",
      systemIntro: "The plan is tailored to your business and budget. These are the connected capabilities we can bring together when they fit the goal.",
      offerings: [["Digital strategy", "Audience, positioning, channel priorities, and a realistic growth roadmap."], ["Website & landing pages", "Clear, responsive experiences that help visitors understand your services and take action."], ["Search & paid media", "SEO and Google Ads aligned to the services, locations, and inquiries that matter."], ["Lead tracking & follow-up", "Measurement and CRM or email connections that help your team respond and learn."]],
      showcaseTitle: "New Jersey-wide reach starts with a clear local focus.", showcaseText: "From Morganville and Monmouth County to businesses serving communities across the state, the right plan reflects where customers are—and what your team can serve well. We avoid copy-and-paste location targeting and build around your real coverage, capacity, and goals.", showcaseImage: "assets/industry-concepts/business-neighborhood-hero-v1.jpg", showcaseAlt: "Independent neighborhood business in a walkable New Jersey downtown", tags: ["Local context", "Connected channels", "Qualified inquiries", "Clear reporting"],
      faq: [["What does digital marketing include?", "Depending on your goals, it can include website strategy and design, SEO, Google Ads, social media, landing pages, analytics, and lead follow-up. We recommend only the pieces that fit your audience and resources."], ["Do you work with businesses outside Morganville?", "Yes. VNW Media is based in Morganville and works with businesses across New Jersey. The service-area plan is based on the communities your business actually serves."], ["Can I start with one service?", "Yes. A project can begin with a priority such as SEO, a website, or paid search, then expand if the results and business needs support it."], ["How do you measure results?", "We agree on practical measures such as qualified calls, form submissions, booked consultations, campaign cost, and relevant search visibility. Reporting depends on the tracking available."], ["Do you guarantee leads or rankings?", "No. Marketing results depend on the market, offer, budget, implementation, and customer experience. We set measurable goals and refine the work, but do not promise specific rankings or lead volumes." ]]
    },
    "seo-new-jersey": {
      region: "new-jersey", service: "SEO", image: "nj-seo.jpg", alt: "A New Jersey business owner and search specialist reviewing a local visibility map and performance charts", proof: "Search visibility, grounded in useful pages", reviewSet: "seo",
      hero: "SEO for New Jersey businesses that want to be found for the right reasons.", lead: "Technical foundations, local relevance, useful service content, and measurement designed around qualified search demand.",
      introTitle: "Build visibility around real services and real service areas.", intro: "SEO is more than adding keywords. We connect technical health, page purpose, local information, customer questions, and internal links so people and search engines can understand what you offer and where you serve.",
      cards: [["Technical health", "Review crawlability, indexation, site structure, redirects, mobile usability, and performance."], ["Local relevance", "Align service-area pages, business details, and local information with the markets you genuinely serve."], ["Useful content", "Improve service pages and FAQs around the questions customers ask before they choose."], ["Measure progress", "Review relevant search visibility alongside calls, forms, and other tracked business actions."]],
      systemTitle: "Make every important page earn its place.", systemIntro: "A sound SEO plan connects the site’s technical foundations to useful pages and an understandable path to action.",
      offerings: [["Search opportunity research", "Prioritize services, questions, and locations that align with business goals."], ["Technical SEO", "Identify and prioritize site issues that may affect discovery or usability."], ["Local SEO", "Improve location relevance without creating thin or misleading coverage pages."], ["Content & reporting", "Create useful page plans and track meaningful changes over time."]],
      showcaseTitle: "Local search should reflect how your New Jersey business operates.", showcaseText: "Whether customers visit a storefront, request an appointment, or need a provider to travel to them, location information should be accurate and useful. We can shape SEO around Monmouth, Middlesex, Ocean, Mercer, and other areas only where they match the business’s actual footprint.", showcaseImage: "assets/service-heroes/seo-performance-review-v1.jpg", showcaseAlt: "Search specialist reviewing SEO performance and organic search charts", tags: ["Technical SEO", "Local visibility", "Service content", "Measurement"],
      faq: [["What is included in SEO?", "Scope can include technical review, search and competitor research, page recommendations, local information, content planning, internal links, and reporting. The mix depends on your website and goals."], ["Can you target several New Jersey towns?", "We can plan useful service-area coverage where it reflects your actual service footprint. We do not recommend publishing near-duplicate city pages just to mention more place names."], ["How long does SEO take?", "SEO is ongoing work, and timing varies by competition, website condition, resources, and search demand. We identify early tasks but do not promise a fixed ranking timeline."], ["Do you guarantee a first-page ranking?", "No. Search results change and depend on many factors outside any agency’s control. Our work focuses on sound implementation and measurable progress."], ["Can SEO work with Google Ads?", "Yes. Organic and paid search can complement one another, especially when service pages, tracking, and conversion paths are coordinated." ]]
    },
    "web-design-new-jersey": {
      region: "new-jersey", service: "Web Design", image: "nj-web-design.jpg", alt: "A web designer discussing a small business website and customer experience with a New Jersey owner", proof: "Websites designed around people and next steps", reviewSet: "web",
      hero: "Web design for New Jersey businesses ready for a better customer experience.", lead: "Create a website that makes your services easier to understand, your business easier to trust, and the next step easier to take.",
      introTitle: "A website should do more than look current.", intro: "Your site is often where a customer decides whether to call, book, visit, or keep looking. We organize content, design, mobile experience, SEO foundations, and conversion paths around that decision.",
      cards: [["Clarify the offer", "Make the most important services, audiences, locations, and differentiators easy to understand."], ["Design for real use", "Create a responsive experience that feels clear on a phone, tablet, and desktop."], ["Build confidence", "Bring the right proof, reviews, project examples, and useful answers into the customer journey."], ["Make action easy", "Connect calls, forms, scheduling, and analytics so customers can act and your team can learn."]],
      systemTitle: "From first impression to confident inquiry.", systemIntro: "The right build depends on your content, systems, audience, and future plans. We shape the structure before polishing the surface.",
      offerings: [["Structure & content", "Sitemap, page goals, content hierarchy, and clear service messaging."], ["Visual design", "A distinct brand experience built for the business and its customers."], ["Development & integrations", "Responsive implementation, forms, CMS connections, and useful integrations."], ["SEO & launch", "Technical foundations, accessibility checks, testing, analytics, and launch support."]],
      showcaseTitle: "Built for local businesses and the way customers choose them.", showcaseText: "A New Jersey service business may need prominent calls and estimate requests. A practice may need clear appointments and provider details. A retail brand may need smoother product discovery. We shape page flow to the business instead of forcing every company into the same template.", showcaseImage: "assets/service-heroes/web-design-customer-engagement-v1.jpg", showcaseAlt: "A customer and web designer reviewing a website on a large screen", tags: ["Mobile-first clarity", "Search-ready structure", "Trust signals", "Conversion paths"],
      faq: [["How much does a business website cost?", "Cost depends on the number of pages, design needs, content, integrations, functionality, and migration or support scope. We define those requirements before proposing a project."], ["Can you redesign my existing New Jersey business website?", "Yes. We can assess the current site and recommend a focused redesign, improvements to key pages, or a new build based on what best supports your goals."], ["Will the website work on mobile?", "Responsive design and mobile review are part of the planning and testing process. The exact experience depends on content, features, and the devices and browsers in scope."], ["Can you help with SEO during a redesign?", "Yes. We can plan URL changes, redirects, page structure, metadata, content, internal links, and technical checks as part of an agreed redesign scope."], ["How long does a website project take?", "Timing depends on project size, content readiness, feedback cycles, integrations, and approvals. We confirm milestones and responsibilities in the project plan." ]]
    },
    "ppc-new-jersey": {
      region: "new-jersey", service: "Google PPC", image: "nj-ppc.jpg", alt: "A paid-search strategist and New Jersey business owner reviewing advertising campaign charts together", proof: "Paid search built around qualified demand", reviewSet: "ppc",
      hero: "Google Ads management for New Jersey businesses seeking qualified demand.", lead: "Plan search campaigns around your services, service area, budget, and the inquiries your team is equipped to handle.",
      introTitle: "Reach active searchers with a campaign built to learn.", intro: "Google Ads can connect a business with people actively looking for a service. Strong management means aligning search intent, geography, landing pages, budgets, tracking, and follow-up—not simply turning ads on.",
      cards: [["Choose the right demand", "Research service intent, campaign types, competitors, and negative-keyword needs."], ["Match the service area", "Set geographic targeting around real operating coverage and campaign capacity."], ["Improve the click-to-lead path", "Align ads with relevant pages, calls, forms, and useful expectations."], ["Measure and optimize", "Review spend, qualified inquiries, and campaign signals to guide careful adjustments."]],
      systemTitle: "Connect campaign setup, landing pages, and follow-up.", systemIntro: "The campaign should fit your budget and ability to respond. We establish measurement and priorities before optimizing for volume.",
      offerings: [["Account & keyword review", "Assess account structure, search terms, service intent, and existing performance."], ["Campaign planning", "Build campaign themes, geographic coverage, budget allocation, and ad direction."], ["Landing-page alignment", "Make sure the destination page answers the ad promise and gives a clear next step."], ["Tracking & optimization", "Review conversion tracking, lead quality, search terms, and agreed performance measures."]],
      showcaseTitle: "Local targeting is only useful when it matches your real coverage.", showcaseText: "Campaigns can focus on Morganville, Monmouth County, or other New Jersey markets where your business can deliver. We account for service radius, customer value, budget, scheduling, and the landing page—not just a list of nearby cities.", showcaseImage: "assets/service-heroes/google-ppc-v2.jpg", showcaseAlt: "Google Ads campaign planning and paid search performance review", tags: ["Search intent", "Geographic strategy", "Conversion tracking", "Lead quality"],
      faq: [["What does Google Ads management include?", "Depending on scope, it can include account audits, keyword and search-term research, campaign structure, ad copy, location settings, landing-page guidance, conversion tracking, and reporting."], ["What budget should a New Jersey business start with?", "There is no universal starting budget. It depends on your services, competition, target areas, economics, and how many qualified inquiries you can handle. Ad spend is separate from management fees."], ["Do you guarantee leads or a cost per lead?", "No. Auction competition, offer, website, seasonality, and audience behavior affect results. We set a measurement plan and work to improve performance without promising a specific volume or cost."], ["Can you target only the towns we serve?", "Campaign locations can be planned around actual service coverage. We review location settings and search terms to reduce spend outside the intended market where campaign controls allow."], ["Should we have a dedicated landing page?", "A focused page can help when it clearly matches the campaign, service, and location. We review the destination experience as part of planning." ]]
    },
    "digital-marketing-new-york": {
      region: "new-york", service: "Digital Marketing", image: "ny-digital-marketing.jpg", alt: "A Brooklyn small-business owner and marketing consultant discussing a connected digital growth plan", proof: "Connected digital growth for New York businesses", reviewSet: "marketing",
      hero: "Digital marketing for New York businesses ready to grow with intention.", lead: "Connect your website, search visibility, campaigns, and lead follow-up around the customers and markets that matter.",
      introTitle: "A coordinated digital plan for a competitive market.", intro: "New York businesses work across distinct neighborhoods, boroughs, and customer expectations. We start with the real service area and business objective, then align website experience, SEO, paid campaigns, social content, and measurement to create a clearer path from discovery to inquiry.",
      cards: [["Understand the market", "Clarify audience, offer, competitors, neighborhood coverage, and the decision customers face."], ["Improve the experience", "Connect message, website pages, proof, and calls to action so the next step is clear."], ["Coordinate discovery", "Bring organic search, paid media, social, and local information into one intentional plan."], ["Measure what matters", "Use qualified calls, forms, bookings, and campaign signals to guide adjustments."]],
      systemTitle: "Connect the channels that support your next move.", systemIntro: "The right combination depends on your goals, internal capacity, and where customers actually come from.",
      offerings: [["Strategy & messaging", "Audience priorities, differentiation, channel roles, and a practical roadmap."], ["Web design & landing pages", "Responsive experiences that make services, neighborhood relevance, and action clear."], ["SEO & local visibility", "Useful pages and accurate business information that support relevant discovery."], ["Google Ads & follow-up", "Campaign structure, lead tracking, and response paths aligned to real capacity."]],
      showcaseTitle: "New York is not one market—and your targeting should not be either.", showcaseText: "A business serving Brooklyn may have a different customer journey from one reaching Manhattan, Queens, Staten Island, Long Island, or communities elsewhere in New York. We shape content and campaigns around the places you genuinely serve, without implying a local office where one does not exist.", showcaseImage: "assets/industry-concepts/business-neighborhood-hero-v1.jpg", showcaseAlt: "Small independent business in a lively New York neighborhood", tags: ["Market-specific planning", "Connected channels", "Lead clarity", "Measurable activity"],
      faq: [["Do you have a physical office in New York?", "VNW Media is based in Morganville, New Jersey, and works with New York businesses through a collaborative remote-first process. We do not represent the location pages as New York offices."], ["Can you work with a business serving multiple boroughs?", "Yes. We can plan service-area coverage, content, and campaign targeting around the places the business truly serves and can support."], ["Which digital marketing services can be combined?", "Depending on the goal, a plan can connect website design, SEO, Google Ads, social media, landing pages, analytics, and lead follow-up."], ["How do you measure marketing across New York?", "We agree on practical measures such as qualified inquiries, calls, booked appointments, campaign spend, and relevant visibility. Reporting depends on the tracking available."], ["Do you guarantee rankings or leads?", "No. Results depend on competition, budget, offer, implementation, and customer experience. We use clear measures and ongoing learning, not guaranteed outcomes." ]]
    },
    "seo-new-york": {
      region: "new-york", service: "SEO", image: "ny-seo.jpg", alt: "A New York business owner and SEO specialist reviewing a map-based visibility report and organic search charts", proof: "Search visibility that reflects your actual market", reviewSet: "seo",
      hero: "SEO for New York businesses that need useful visibility—not empty traffic.", lead: "Technical SEO, local relevance, service content, and measurement built around the searches your customers use.",
      introTitle: "Make your expertise clear across the places you serve.", intro: "In a dense and varied search market, SEO needs to distinguish your services and coverage clearly. We review technical foundations, page intent, local information, useful content, and internal links to support discovery and qualified action.",
      cards: [["Strengthen technical foundations", "Review crawlability, indexation, mobile usability, structure, and page performance."], ["Clarify local relevance", "Make service and location information accurate for the neighborhoods and communities you serve."], ["Answer customer questions", "Improve pages and FAQs around the decisions people make before contacting a provider."], ["Measure quality, not just visits", "Connect relevant search visibility to tracked inquiries and meaningful customer actions."]],
      systemTitle: "A strong SEO plan is built page by page.", systemIntro: "Clear technical signals, purposeful content, and trustworthy business information reinforce each other.",
      offerings: [["Search demand research", "Prioritize queries, services, and location needs that make sense for the business."], ["Technical SEO", "Investigate indexing, structure, redirects, performance, and other site-health factors."], ["Local SEO", "Improve business facts, service areas, and location content without overstating coverage."], ["Content & measurement", "Plan useful service pages and monitor visibility with business outcomes where trackable."]],
      showcaseTitle: "Build New York location relevance without pretending every neighborhood is an office.", showcaseText: "A page should help customers understand whether you serve them and what to expect. We map useful content to real operations—whether your business serves one borough, several neighborhoods, or a wider part of New York—and avoid repetitive pages made only to insert place names.", showcaseImage: "assets/service-heroes/seo-performance-review-v1.jpg", showcaseAlt: "SEO consultant analyzing organic traffic and search performance", tags: ["Technical SEO", "Local coverage", "Helpful content", "Business outcomes"],
      faq: [["Can you do SEO for New York City and multiple boroughs?", "We can plan relevant service and location coverage for the areas your business genuinely serves. The page plan depends on distinct services, operations, and customer needs."], ["Do location pages guarantee visibility in each borough?", "No. Creating a page does not guarantee rankings or local results. Useful content, technical foundations, competition, business signals, and ongoing quality all matter."], ["How long before SEO improves?", "Timing varies by starting condition, competition, search demand, resources, and implementation. We can prioritize technical fixes and page work but do not promise a fixed timeline."], ["Can you work with our current website team?", "Yes. We can provide audits, priorities, content direction, and implementation guidance, or coordinate tasks according to the agreed project scope."], ["Can you combine SEO with Google Ads?", "Yes. Search pages and paid campaigns can support one another when they share a clear offer, accurate location context, and useful measurement." ]]
    },
    "web-design-new-york": {
      region: "new-york", service: "Web Design", image: "ny-web-design.jpg", alt: "A New York web designer presenting a website concept to a small-business owner in a Brooklyn studio", proof: "Web experiences for the way New Yorkers choose", reviewSet: "web",
      hero: "Web design for New York businesses that want every visit to feel clearer.", lead: "Present your services with confidence, make the experience work on mobile, and help the right customer take the next step.",
      introTitle: "Make a crowded choice feel simple.", intro: "A website can help a New York customer quickly understand what you offer, where you operate, what makes you credible, and how to begin. We design content and page flow around those decisions—not just a visual refresh.",
      cards: [["Show what makes you different", "Clarify services, audience, expertise, and reasons customers choose you."], ["Design for mobile behavior", "Keep important information and actions accessible on the devices people use every day."], ["Earn confidence", "Use real proof, useful content, reviews, and clear expectations to reduce uncertainty."], ["Support the next action", "Connect calls, forms, bookings, and analytics to the actual business process."]],
      systemTitle: "A website system designed for discovery and action.", systemIntro: "Page structure and features follow your business model, content, systems, and customer journey.",
      offerings: [["Discovery & structure", "Goals, audiences, sitemap, page purposes, and content hierarchy."], ["Design & development", "A distinctive responsive visual system and tested website implementation."], ["Content & conversion", "Clear service content, calls to action, and useful trust signals."], ["Technical launch", "SEO foundations, integrations, redirects where needed, quality checks, and launch support."]],
      showcaseTitle: "One website should serve the right customers—not every audience at once.", showcaseText: "A Brooklyn retailer, a Manhattan professional service, and a company serving several boroughs need different paths to contact and conversion. We plan relevant service and location information around your operations and give visitors a direct way to understand fit.", showcaseImage: "assets/service-heroes/web-design-customer-engagement-v1.jpg", showcaseAlt: "Designer and client discussing a website experience together", tags: ["Distinctive design", "Mobile usability", "Trust & proof", "Clear conversion"],
      faq: [["How much does web design cost in New York?", "Project cost depends on page count, content, design requirements, integrations, functionality, migration, and support. We clarify scope before providing a proposal."], ["Can the site serve multiple boroughs or regions?", "Yes. We can organize service and location information for areas you truly serve, while keeping page content distinct and useful."], ["Will you work with our existing branding and platform?", "We can assess your current brand, CMS, and integrations and recommend what to retain, improve, or replace based on the project goals."], ["Can you help us improve our existing site instead of rebuilding?", "Yes. Sometimes improving key pages, navigation, mobile usability, or lead flow is the better first step. We can review and recommend a practical scope."], ["How long does a website project take?", "Timing depends on complexity, content, approvals, integrations, and feedback cycles. The project plan sets milestones and responsibilities." ]]
    },
    "ppc-new-york": {
      region: "new-york", service: "Google PPC", image: "ny-ppc.jpg", alt: "A New York search-marketing consultant and local business owner reviewing paid campaign results", proof: "Campaigns aligned to real New York service areas", reviewSet: "ppc",
      hero: "Google Ads management for New York businesses focused on better-fit leads.", lead: "Connect search intent, campaign geography, landing pages, budgets, and measurement around the leads your team can serve.",
      introTitle: "Paid search works best when every step agrees.", intro: "Campaign results depend on more than bids. We align keywords, locations, ad promise, landing page, calls or forms, and lead follow-up so each part supports a meaningful business action.",
      cards: [["Prioritize high-intent searches", "Separate relevant service demand from broad or low-fit traffic."], ["Set sensible geography", "Shape campaigns around the actual neighborhoods and service areas your team can support."], ["Make the landing experience relevant", "Match the page to the search, offer, location, and next action."], ["Optimize with useful signals", "Review spending, search terms, and lead quality alongside available conversion data."]],
      systemTitle: "Build campaigns with clear controls and useful feedback.", systemIntro: "Planning balances opportunity, budget, competition, and operational capacity—then uses measurement to inform refinements.",
      offerings: [["Account assessment", "Review structure, targeting, conversion setup, search terms, and opportunities."], ["Campaign strategy", "Plan search themes, geographic coverage, budget, and ad direction."], ["Landing-page alignment", "Connect each ad to a focused page with matching information and action."], ["Measurement & improvement", "Check tracking, lead quality, and campaign performance against agreed priorities."]],
      showcaseTitle: "Target the New York areas you can actually support.", showcaseText: "The right campaign boundaries depend on service coverage, location, scheduling, customer value, and available budget. We plan with those realities in mind and review location settings and search terms to keep the effort relevant.", showcaseImage: "assets/service-heroes/google-ppc-v2.jpg", showcaseAlt: "Search campaign manager reviewing paid advertising performance", tags: ["Search intent", "Location controls", "Landing pages", "Lead quality"],
      faq: [["Do you manage Google Ads for businesses in New York?", "Yes. We can plan and manage Google Ads for New York businesses, including account review, campaign setup, optimization, and reporting as defined in the project scope."], ["Can you target specific boroughs or neighborhoods?", "Campaign geography can be configured around the business’s actual coverage. We confirm the intended area and review settings so the targeting fits operational capacity."], ["How much does Google Ads cost?", "Ad budget varies with services, competition, geography, and lead economics. Media spend is separate from management fees; we help define a responsible test budget based on the opportunity."], ["Can you promise a certain cost per lead?", "No. Auction dynamics, competition, offer, page experience, and follow-up influence cost and volume. We establish tracking and optimize against agreed measures without guaranteeing a specific outcome."], ["Do we need a separate page for every borough?", "Not automatically. A page is useful when it serves a distinct customer need and can provide genuinely relevant information. We avoid thin or repetitive location pages." ]]
    }
  };

  function escapeHtml(value) {
    return String(value).replace(/[&<>"']/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
  }
  function heroFormMarkup(data, facts) {
    const interest = `${data.service} in ${facts.state}`;
    return `<form class="hero-form indl-hero-form location-hero-form" aria-label="Plan your ${escapeHtml(interest)} strategy">
      <h2>Plan your ${escapeHtml(data.service)} growth strategy</h2>
      <label class="icon-field"><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/></svg><input name="name" autocomplete="name" required placeholder="Full Name" aria-label="Full Name" /></label>
      <label class="icon-field"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M3 10h18"/><path d="M5 10V7l7-4 7 4v3"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/></svg><input name="company" autocomplete="organization" required placeholder="Business Name" aria-label="Business Name" /></label>
      <label class="icon-field"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1.9.3 1.8.6 2.6a16 16 0 0 0 6.3 6.3l1.3-1.3a2 2 0 0 1 2.1-.4c.8.3 1.7.5 2.6.6a2 2 0 0 1 1.7 2z"/></svg><input name="phone" type="tel" autocomplete="tel" required placeholder="Phone Number" aria-label="Phone Number" /></label>
      <label class="icon-field"><svg aria-hidden="true" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg><input name="email" type="email" autocomplete="email" required placeholder="Email Address" aria-label="Email Address" /></label>
      <label class="icon-field"><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/></svg><input name="website" type="url" autocomplete="url" placeholder="Website (Optional)" aria-label="Website (Optional)" /></label>
      <input type="hidden" name="interest" value="${escapeHtml(interest)}" />
      <button type="submit">Plan my next step</button><p class="form-status" role="status" aria-live="polite"></p>
    </form>`;
  }
  function cardMarkup(items, className = "indl-card-grid") {
    return `<div class="${className}">${items.map((item, i) => `<article><span>0${i + 1}</span><h3>${escapeHtml(item[0])}</h3><p>${escapeHtml(item[1])}</p></article>`).join("")}</div>`;
  }
  function reviewMarkup(key) {
    return `<section class="location-reviews" id="client-reviews" data-nav-theme="dark"><div class="shell"><div class="location-reviews-head"><div><p class="section-tag">Client Feedback</p><h2>Trusted by the people behind growing businesses.</h2></div><div class="location-rating"><span aria-hidden="true">★★★★★</span><strong>4.9</strong><small>on Google</small></div></div><div class="location-review-grid">${reviews[key].map(([name, quote]) => `<figure><span>Google review · ★★★★★</span><blockquote>“${escapeHtml(quote)}”</blockquote><figcaption>${escapeHtml(name)}</figcaption></figure>`).join("")}</div><a class="text-arrow" href="${reviewsUrl}" target="_blank" rel="noopener">Read VNW Media Google reviews <span>↗</span></a><p class="location-review-note">These are VNW Media client reviews and are not represented as reviews from a particular city or service area.</p></div></section>`;
  }
  function pageMarkup(data, facts) {
    const options = data.offerings.map((item, i) => `<article><span>0${i + 1}</span><div><h3>${escapeHtml(item[0])}</h3><p>${escapeHtml(item[1])}</p></div></article>`).join("");
    const faq = data.faq.map(([question, answer], i) => `<details${i === 0 ? " open" : ""}><summary>${escapeHtml(question)}<span aria-hidden="true">+</span></summary><p>${escapeHtml(answer)}</p></details>`).join("");
    const tags = data.tags.map(tag => `<span>${escapeHtml(tag)}</span>`).join("");
    const siblingLinks = Object.entries(pages).filter(([slug, other]) => slug !== document.body.dataset.locationPage && other.region === data.region).map(([slug, other]) => `<a href="${asset(`locations/${other.region}/${slug}/`)}">${escapeHtml(other.service)} in ${facts.state}<span aria-hidden="true">↗</span></a>`).join("");
    return `<main id="top" class="location-main">
      <section class="indl-hero location-hero" data-nav-theme="dark"><div class="indl-hero-media"><img src="${asset(`assets/location-heroes/${data.image}`)}" alt="${escapeHtml(data.alt)}" fetchpriority="high"></div><div class="indl-hero-shade"></div><div class="shell indl-hero-inner"><div class="indl-hero-copy"><p class="section-tag">${escapeHtml(data.service)} · ${facts.state}</p><h1>${escapeHtml(data.hero)}</h1><p>${escapeHtml(data.lead)}</p><div class="indl-actions"><a class="pill pill-blue pill-large" href="${contact}">Discuss ${escapeHtml(data.service)} in ${facts.state} <span>↗</span></a><a class="pill pill-outline pill-large" href="#local-approach">Explore the approach</a></div></div>${heroFormMarkup(data, facts)}</div></section>
      <section class="trust-strip indl-ticker location-ticker" aria-label="${escapeHtml(data.service)} focus areas"><div class="trust-track"><small>Built around your market</small><i></i><span>${escapeHtml(data.service)}</span><span>Customer experience</span><span>Search visibility</span><span>Local relevance</span><span>Qualified leads</span><span>Clear measurement</span><span>Practical next steps</span></div></section>
      <section class="indl-showcase mockup-direction-section location-showcase" data-nav-theme="light"><div class="shell indl-showcase-grid"><div class="indl-showcase-media"><img src="${asset(data.showcaseImage)}" alt="${escapeHtml(data.showcaseAlt)}" loading="lazy"></div><article class="indl-showcase-copy"><p class="section-tag">Local market context</p><h2>${escapeHtml(data.showcaseTitle)}</h2><p>${escapeHtml(data.showcaseText)}</p><div class="indl-tags">${tags}</div><a class="text-arrow" href="${contact}">Plan your next step <span>↗</span></a></article></div></section>
      <section class="indl-section industry-system-section location-system" id="local-approach" data-nav-theme="light"><div class="shell food-menu-board"><aside><p class="section-tag">How the work fits together · One connected approach</p><h2>${escapeHtml(data.systemTitle)}</h2><p><strong>${escapeHtml(data.service)} for ${facts.state}.</strong> ${escapeHtml(data.systemIntro)}</p><p>${escapeHtml(facts.context)}</p><a class="pill pill-blue" href="${contact}">Discuss your project <span>↗</span></a></aside><div class="food-menu-list">${options}</div></div></section>
      <section class="indl-section location-overview decision-section" data-nav-theme="light"><div class="shell"><div class="indl-head"><p class="section-tag">${escapeHtml(data.service)} in ${facts.state}</p><h2>${escapeHtml(data.introTitle)}</h2><p>${escapeHtml(data.intro)}</p><p class="location-area-note"><strong>Markets we can discuss</strong><br>${escapeHtml(facts.places)}. Coverage is confirmed against your actual service area.</p></div>${cardMarkup(data.cards)}</div></section>
      ${reviewMarkup(data.reviewSet)}
      <section class="indl-section location-related" data-nav-theme="light"><div class="shell"><div class="indl-head"><div><p class="section-tag">More in ${facts.state}</p><h2>Related digital growth services.</h2></div><div><p>Explore connected areas that may support the same business goal. We’ll help you prioritize what fits rather than assume every service is needed.</p></div></div><div class="location-related-links">${siblingLinks}<a href="${services}">View all VNW Media services<span aria-hidden="true">↗</span></a></div></div></section>
      <section class="indl-final location-final" data-nav-theme="dark"><div class="shell"><p class="section-tag">Plan a clear next step</p><h2>Let’s make your next digital move work harder.</h2><p>Tell us what you offer, where you work, and what you want your marketing to accomplish. We’ll help you identify a practical place to begin.</p><div class="indl-final-actions"><a class="pill pill-blue pill-large" href="${contact}">Talk with VNW Media <span>↗</span></a><a class="pill pill-outline pill-large" href="tel:17328200609">Call (732) 820-0609</a></div></div></section>
      <section class="indl-faq location-faq" id="faq" data-nav-theme="light"><div class="shell indl-faq-grid"><div class="indl-faq-intro"><p class="section-tag">${escapeHtml(data.service)} in ${facts.state} · FAQs</p><h2>Useful answers before we begin.</h2><p>Every project depends on the business, market, and priorities. Here are a few common questions.</p><a class="pill pill-blue" href="${contact}">Ask about your project <span>↗</span></a></div><div class="indl-faq-list">${faq}</div></div></section>
    </main>`;
  }
  function directoryMarkup(regionOnly = "") {
    const states = Object.entries(areaFacts).filter(([slug]) => !regionOnly || slug === regionOnly);
    const stateCards = states.map(([slug, facts]) => {
      const childLinks = Object.entries(pages).filter(([, page]) => page.region === slug).map(([pageSlug, page]) => `<a href="${asset(`locations/${slug}/${pageSlug}/`)}">${escapeHtml(page.service)} in ${facts.state}<span aria-hidden="true">↗</span></a>`).join("");
      return `<section class="location-state-card"><p class="section-tag">${facts.state}</p><h2>Digital growth for ${facts.state} businesses.</h2><p>${escapeHtml(facts.context)}</p><div>${childLinks}</div></section>`;
    }).join("");
    return `<main id="top" class="location-directory"><section class="location-directory-hero"><div class="shell"><p class="section-tag">VNW Media · Service areas</p><h1>Local knowledge. Connected digital growth.</h1><p>Explore location-specific digital marketing, SEO, web design, and Google Ads pages for New Jersey and New York.</p></div></section><div class="shell location-state-grid">${stateCards}</div><section class="location-directory-cta"><div class="shell"><h2>Need help choosing a place to start?</h2><p>Tell us where you operate and what you want to improve.</p><a class="pill pill-blue" href="${contact}">Talk with VNW Media <span>↗</span></a></div></section></main>`;
  }
  const pageId = document.body.dataset.locationPage;
  const app = document.getElementById("app");
  if (pageId && pages[pageId]) app.innerHTML = pageMarkup(pages[pageId], areaFacts[pages[pageId].region]);
  else if (document.body.dataset.locationDirectory === "true") app.innerHTML = directoryMarkup(document.body.dataset.locationRegion || "");
})();
