from pathlib import Path
from html import escape
root=Path(__file__).resolve().parents[1]
qs=[('A website that fits today.','Bring your services, message, and contact experience back into alignment.'),('Marketing with a shared direction.','Connect your website, search presence, and campaigns around the same priorities.'),('A clearer place to begin.','Talk through the challenge before deciding which services you need.')]
intro='Our New Jersey web design and digital marketing team helps turn your business priorities into a practical project scope.'
def btn(text='Let’s talk about your business'):return '<a class="nc-button" href="contact.html">'+text+'</a>'
def photo(slug,alt):return f'<img src="assets/service-heroes/{slug}-v2.jpg" alt="{alt}" loading="lazy">'
def items():return ''.join(f'<article><span class="nc-number">0{i+1}</span><h3>{q}</h3><p>{a}</p></article>' for i,(q,a) in enumerate(qs))
def tag(t='Your next chapter'):return '<p class="nc-eyebrow">'+t+'</p>'
options=[]
def add(name,note,cls,body):options.append((name,note,cls,body))
add('The Editorial','A quiet ivory canvas, oversized serif headline, and a ruled service index.','editorial light',f'<div class="nc-wrap"><div class="nc-lead">{tag()}<h2>You know your business.<br><em>Let’s shape what’s next.</em></h2></div><div class="nc-editorial-bottom"><div><p>{intro}</p>{btn()}</div><div class="nc-index">{items()}</div></div></div>')
add('The Working Session','A warm photographic split with a dark, focused conversation panel.','session dark',f'<div class="nc-session-photo">{photo("brand-strategy","Creative team discussing a business direction")}<span>Good work begins with a conversation.</span></div><div class="nc-session-copy">{tag("A shared direction")}<h2>Your next move.<br><em>Thought through together.</em></h2><p>{intro}</p><div class="nc-compact">{items()}</div>{btn("Talk through your priorities")}</div>')
add('Choose Your Starting Point','Three photographic cards turn the business challenges into clear choices.','cards light',f'<div class="nc-wrap"><div class="nc-heading-row"><div>{tag()}<h2>Where should<br><em>we begin?</em></h2></div><p>You bring the business context. We help find the right starting point.</p></div><div class="nc-card-grid">'+''.join(f'<article>{photo(slug,alt)}<div><span class="nc-number">0{i+1}</span><h3>{q}</h3><p>{a}</p><a class="nc-link" href="contact.html">Let’s discuss it</a></div></article>' for i,((q,a),slug,alt) in enumerate(zip(qs,['web-design','seo','brand-strategy'],['Designers reviewing a business website','Specialists reviewing search performance','Team planning a brand direction'])))+'</div></div>')
add('The Statement','A bold black section with cyan typography and three numbered priorities.','statement dark',f'<div class="nc-wrap">{tag("One business. One direction.")}<h2>Less scattered.<br><em>More connected.</em></h2><div class="nc-statement-bottom"><p>Your website, search presence, and campaigns should tell the same story. Let’s decide what needs to happen next.</p>{btn("Start the conversation")}</div><div class="nc-three">{items()}</div></div>')
add('The Conversation','An open, spacious question-and-answer layout that invites visitors to explore.','conversation light',f'<div class="nc-wrap nc-split"><div>{tag("Does this sound familiar?")}<h2>A better direction<br>starts with<br><em>a better question.</em></h2><p>{intro}</p>{btn("Tell us what’s on your mind")}</div><div class="nc-questions">'+''.join(f'<details {"open" if i==0 else ""}><summary><span>0{i+1}</span>{q}<small>Read</small></summary><p>{a}</p><a class="nc-link" href="contact.html">Talk about this</a></details>' for i,(q,a) in enumerate(qs))+'</div></div>')
add('The Cinematic Invitation','A single full-width photograph with a readable dark overlay and concise closing message.','cinema dark',f'{photo("crm-automation","Colleagues planning connected customer follow-up")}<div class="nc-wrap"><div class="nc-cinema-copy">{tag()}<h2>Bring the pieces<br><em>into focus.</em></h2><p>{intro}</p>{btn()}</div><div class="nc-cinema-footer"><span>Your website.</span><span>Your visibility.</span><span>Your next conversation.</span></div></div>')
add('The Three Chapters','Alternating light and dark panels create a strong editorial rhythm.','chapters light',f'<div class="nc-wrap"><div class="nc-heading-row"><div>{tag("A practical way forward")}<h2>One priority.<br><em>A clearer plan.</em></h2></div><div><p>{intro}</p>{btn("Plan your next chapter")}</div></div><div class="nc-chapter-grid">'+''.join(f'<article><span class="nc-number">0{i+1} / {label}</span><h3>{q}</h3><p>{a}</p></article>' for i,((q,a),label) in enumerate(zip(qs,['Reflect','Connect','Focus'])))+'</div></div>')
add('The Priority Selector','An interactive dark panel lets visitors choose their challenge and see a relevant next step.','selector dark',f'<div class="nc-wrap">{tag("Start with your business")}<h2>What would you<br><em>like to change?</em></h2><div class="nc-tabs" role="tablist" aria-label="Business priorities">'+''.join(f'<button id="nc-tab-{i}" role="tab" aria-selected="{str(i==0).lower()}" aria-controls="nc-panel-{i}" tabindex="{0 if i==0 else -1}" data-nc-tab="{i}">{label}</button>' for i,label in enumerate(['My website','My marketing','My next step']))+'</div>'+''.join(f'<div class="nc-panel" id="nc-panel-{i}" role="tabpanel" aria-labelledby="nc-tab-{i}" {"hidden" if i else ""}>{photo(slug,alt)}<div><span class="nc-number">0{i+1}</span><h3>{q}</h3><p>{a}</p>{btn("Discuss this priority")}</div></div>' for i,((q,a),slug,alt) in enumerate(zip(qs,['web-design','google-ppc','brand-strategy'],['Team reviewing a website','Marketing team discussing campaign performance','Colleagues planning a business strategy'])))+'</div>')
add('The Shared Plan','A restrained process strip connects business understanding, priorities, and scope.','plan light',f'<div class="nc-wrap nc-plan-top"><div>{tag("From business context to project scope")}<h2>You bring the ambition.<br><em>We bring the perspective.</em></h2></div>{photo("brand-strategy","Team collaborating on brand and business priorities")}</div><div class="nc-plan-bottom"><div class="nc-wrap"><div class="nc-three">'+''.join(f'<article><span class="nc-number">0{i+1}</span><h3>{h}</h3><p>{p}</p></article>' for i,(h,p) in enumerate([('Understand your business.','Talk about your audience, goals, and what no longer fits.'),('Choose the priority.','Decide where a stronger website or more connected marketing could help.'),('Define the next step.','Turn that priority into a practical scope before the work begins.')]))+f'</div><div class="nc-plan-cta"><p>A useful conversation before a list of services.</p>{btn("Let’s make a plan")}</div></div></div>')
add('The Open Letter','A personal, centered invitation with dramatic serif type and a simple text footer.','letter dark',f'<div class="nc-wrap">{tag("To the business ready for its next chapter")}<h2>You’ve built something<br>worth knowing.<br><em>Let’s help it show.</em></h2><p>When your website no longer fits, your marketing feels disconnected, or the next step is unclear, start with a conversation.</p>{btn()}<div class="nc-letter-bottom"><span>New Jersey team.</span><span>Business-first thinking.</span><span>A practical next step.</span></div></div>')
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Case Studies Section Designs | VNW Media</title><link rel="stylesheet" href="styles.css?v=227"><link rel="stylesheet" href="case-next-chapter-options.css?v=1"><link rel="stylesheet" href="site-footer.css?v=1"><script defer src="service-catalog.js?v=20260914-heroes"></script><script defer src="script.js?v=145"></script><script defer src="site-footer.js?v=1"></script><script defer src="case-next-chapter-options.js?v=1"></script></head><body class="nc-review"><header class="site-header"></header><main id="nc-review"><header class="nc-overview nc-wrap"><p class="nc-eyebrow">Case Studies / Section design review</p><h1>Ten ways to begin<br>the next chapter.</h1><p>Alternative designs for the “You know your business” section only. The live Case Studies page is unchanged.</p><nav aria-label="Choose a design">'''+''.join(f'<a href="#design-{i+1}">{i+1:02} {name}</a>' for i,(name,*_) in enumerate(options))+'''</nav></header>'''
for i,(name,note,cls,body) in enumerate(options):html+=f'<div class="nc-review-label" id="design-{i+1}"><div class="nc-wrap"><div><strong>{i+1:02} / {name}</strong><p>{note}</p></div><a href="#nc-review">All designs</a></div></div><section class="nc-option {cls}" aria-label="Design {i+1}: {name}">{body}</section>'
html+='</main></body></html>'
(root/'case-next-chapter-options.html').write_text(html)
