// Editorial source for the industry directory and its focused service pages.
// Keep claims about client work tied to the verified case-study URLs below.
export const industries = [
  {
    slug: 'home-services', name: 'Home Services', label: 'Home Services & Contractors', image: 'home-services.png',
    imageAlt: 'Home-services contractor discussing a project with a homeowner at the front porch',
    hero: 'Make it easier for homeowners to find, trust, and contact your team.',
    intro: 'A homeowner may need help urgently, or may spend weeks comparing estimates. We shape the website, search presence, reviews, and campaigns around the service, the service area, and the next practical step.',
    audience: 'homeowners comparing local contractors and service providers',
    choice: 'clear service details, real project proof, availability, and a straightforward estimate request',
    action: 'qualified calls and estimate requests',
    local: 'service-area boundaries, emergency availability, and individual service lines',
    secondTitle: 'Contractor SEO', secondSlug: 'contractor-seo', secondFocus: 'Trade-specific service pages should distinguish the work you actually perform, the communities you serve, and the proof behind your team.',
    profileFocus: 'A service-area business may not need a public storefront address. Profile setup should reflect actual eligibility, business hours, categories, and real coverage.',
    ppcTitle: 'PPC for Home Services', ppcFocus: 'Separate urgent repairs from planned projects, then align each search theme with the right service page, schedule, and lead response.',
    reputationFocus: 'Reviews should help homeowners understand reliability, communication, workmanship, and what happens after an estimate.',
    designFocus: 'Give each major service a useful page, make phone and estimate actions easy on mobile, and show authentic project evidence.',
    process: [['Understand the job', 'Separate emergency needs from considered projects and identify the service lines that matter most.'], ['Show the proof', 'Present real work, service boundaries, reviews, and expectations before the customer calls.'], ['Make contact simple', 'Connect calls and estimate forms to a follow-up process the team can support.']],
    cases: [['H2Bros Plumbing', 'h2bros-plumbing.html'], ['Catanzaro’s Power Washing', 'catanzaros-power-washing.html'], ['Art of Construction', 'art-of-construction.html']]
  },
  {
    slug: 'healthcare', name: 'Healthcare', label: 'Healthcare Practices', image: 'healthcare.png',
    imageAlt: 'Healthcare team speaking with a patient in a contemporary clinic',
    hero: 'Help patients understand care and take the next step with confidence.',
    intro: 'People looking for a provider need clear services, useful answers, location and appointment details, and reasons to trust the practice. We build digital experiences that explain care without replacing professional advice or making outcome promises.',
    audience: 'patients and caregivers comparing providers, services, and appointment options',
    choice: 'plain-language service information, provider context, accessibility, and an easy appointment path',
    action: 'appropriate appointment inquiries',
    local: 'practice locations, provider specialties, appointment availability, and accessibility information',
    secondTitle: 'Medical Practice SEO', secondSlug: 'medical-practice-seo', secondFocus: 'Organize conditions, services, providers, and locations so useful information is easy to discover while clinical claims remain reviewable by the practice.',
    profileFocus: 'Keep eligible practice locations, hours, categories, appointment links, and contact details accurate; do not imply a provider works at a location where they do not.',
    ppcTitle: 'PPC for Healthcare', ppcFocus: 'Match service intent to a clear appointment page, with privacy-aware measurement and copy reviewed against the practice’s advertising requirements.',
    reputationFocus: 'Invite feedback responsibly and respond with care, without disclosing patient information or pressuring people to share health details.',
    designFocus: 'Clarify treatments, providers, insurance or payment information where supplied, accessibility, and appointment choices on every screen.',
    process: [['Clarify care', 'Organize services and provider information around the questions patients actually bring.'], ['Build confidence', 'Use accurate practice details, useful explanations, and approved trust signals.'], ['Support appointments', 'Make contact and scheduling clear while treating privacy and accessibility as design requirements.']],
    cases: [['Vision Centers', 'vision-centers.html']]
  },
  {
    slug: 'automotive', name: 'Automotive', label: 'Automotive & Auto Body', image: 'automotive.png',
    imageAlt: 'Auto repair technician talking with a customer in a working service bay',
    hero: 'Turn a stressful vehicle decision into a clear path to service.',
    intro: 'Drivers need to know what a shop does, whether it handles their vehicle or repair, where it is, and how to book or request an estimate. We connect local search, proof, paid demand, and a mobile-ready website around that decision.',
    audience: 'drivers comparing repair shops, collision centers, and vehicle services',
    choice: 'repair capabilities, certifications where applicable, reviews, location, and a clear estimate or booking path',
    action: 'service bookings and qualified estimate requests',
    local: 'shop locations, service specialties, vehicle types, and real appointment capacity',
    secondTitle: 'Auto Body SEO', secondSlug: 'auto-body-seo', secondFocus: 'Collision searches call for specific repair information, estimate expectations, insurance-process clarity, and credible shop proof—not generic “auto repair” copy.',
    profileFocus: 'Keep each eligible shop profile aligned with its true location, service categories, hours, photos, and appointment options.',
    ppcTitle: 'PPC for Auto Repair', ppcFocus: 'Separate maintenance, diagnostics, and collision intent so spend is directed toward jobs the shop is equipped to accept.',
    reputationFocus: 'Make it easy for customers to understand service quality and communication through genuine reviews and thoughtful, non-defensive responses.',
    designFocus: 'Show repair categories, shop proof, hours, location, and estimate or booking actions before a driver has to hunt for them.',
    process: [['Identify the repair', 'Separate maintenance, collision, and specialty searches so each page answers the right need.'], ['Establish confidence', 'Show capabilities, real shop work, customer feedback, and clear service expectations.'], ['Create a next step', 'Connect calls, booking, and estimate requests to the team’s actual workflow.']],
    cases: [['Brooklyn Motors', 'brooklyn-motors.html']]
  },
  {
    slug: 'restaurants-hospitality', name: 'Restaurants & Hospitality', label: 'Restaurants & Hospitality', image: 'restaurants-hospitality.png',
    imageAlt: 'Restaurant owner welcoming guests in a neighborhood dining room',
    hero: 'Make the experience compelling before a guest walks in.',
    intro: 'A guest may discover a restaurant through search, a map, a recommendation, or an event listing. We help the digital experience answer the immediate questions: what is it like, where is it, when is it open, and how do I reserve, order, or visit?',
    audience: 'diners and guests choosing where to eat, stay, celebrate, or gather',
    choice: 'current menus or offerings, atmosphere, hours, location, availability, and an easy reservation or order path',
    action: 'reservations, orders, calls, and visits',
    local: 'individual venues, hours, menus, delivery boundaries, and event offerings',
    secondTitle: 'Hospitality SEO', secondSlug: 'hospitality-seo', secondFocus: 'Give each venue, experience, and occasion genuinely useful content instead of repeating the same menu and neighborhood terms.',
    profileFocus: 'Keep each eligible venue’s hours, address, category, photos, menu or booking links, and holiday updates current.',
    ppcTitle: 'PPC for Restaurants', ppcFocus: 'Plan campaigns around high-intent occasions, reservations, catering, and local demand with landing pages that match the offer.',
    reputationFocus: 'Use genuine guest feedback to learn about food, service, and atmosphere, and respond professionally without promising every experience is identical.',
    designFocus: 'Put the menu or offering, location, hours, booking, and real photography within easy reach on mobile.',
    process: [['Show the experience', 'Use real venue information and photography that matches what guests can expect.'], ['Answer practical questions', 'Keep hours, menus, location, events, and booking paths easy to find.'], ['Connect the visit', 'Align discovery with reservations, orders, calls, and in-person demand.']],
    cases: [['La Rosa Chicken & Grill', 'la-rosa-chicken-grill.html']]
  },
  {
    slug: 'daycare-education', name: 'Daycare & Education', label: 'Daycare & Education', image: 'daycare-education.png',
    imageAlt: 'Early-childhood educator speaking with a parent in a daycare classroom',
    hero: 'Give families the clarity they need to begin a conversation.',
    intro: 'Families make careful decisions about care and learning. We organize programs, age groups, daily experience, location, staff information, and inquiry steps so a parent can judge fit and ask the right questions.',
    audience: 'parents and caregivers comparing care and learning programs',
    choice: 'program details, age ranges, safety practices, staff context, location, and a tour or enrollment path',
    action: 'qualified tour and enrollment inquiries',
    local: 'campus locations, age groups, schedules, program availability, and tour capacity',
    secondTitle: 'Education SEO', secondSlug: 'education-seo', secondFocus: 'Build distinct pages for actual programs, age groups, and campuses, with useful enrollment details rather than interchangeable location copy.',
    profileFocus: 'Keep eligible campus profiles accurate and make the correct program, hours, contact, and tour information easy to reach.',
    ppcTitle: 'PPC for Daycare', ppcFocus: 'Align parent searches to age-appropriate program pages, real availability, geographic fit, and a clear tour request.',
    reputationFocus: 'Present family feedback respectfully and protect children’s privacy in review requests, responses, and photos.',
    designFocus: 'Make programs, schedules, campus details, staff information, safety approach, and tour requests clear without overloading the page.',
    process: [['Explain the program', 'Show age groups, daily structure, and what makes the experience distinct.'], ['Respect family questions', 'Make safety, staff, location, and practical enrollment details easy to find.'], ['Invite a conversation', 'Give families a simple path to ask, visit, and understand current availability.']],
    cases: []
  },
  {
    slug: 'legal-professional-services', name: 'Legal & Professional Services', label: 'Legal & Professional Services', image: 'legal-professional-services.png',
    imageAlt: 'Professional advisor listening to a small-business client in an office meeting',
    hero: 'Make expertise understandable before the first conversation.',
    intro: 'A prospective client wants to know whether a firm handles their matter, how the engagement begins, and what makes the team credible. We build clear practice-area content and an inquiry path while keeping claims subject to the firm’s review.',
    audience: 'people and businesses evaluating professional counsel or specialist services',
    choice: 'practice-area fit, team credentials, process expectations, and a confidential contact path',
    action: 'relevant consultation inquiries',
    local: 'practice areas, jurisdictions or service reach, office locations, and intake capacity',
    secondTitle: 'Professional Services SEO', secondSlug: 'professional-services-seo', secondFocus: 'Organize substantive service pages around the actual questions and decision points clients face, with professional review of sensitive claims.',
    profileFocus: 'Keep eligible office profiles, hours, practitioner information, and contact links consistent with the firm’s real operations.',
    ppcTitle: 'PPC for Legal & Professional Services', ppcFocus: 'Separate practice-area intent and geography, review ad language carefully, and measure qualified consultations rather than raw clicks.',
    reputationFocus: 'Use feedback and responses carefully, preserving confidentiality and avoiding claims that imply a guaranteed result.',
    designFocus: 'Present practice areas, people, process, trust signals, and a discreet contact path in a calm, accessible experience.',
    process: [['Define fit', 'Clarify the matters or engagements the team actually handles.'], ['Explain the process', 'Set useful expectations without promising a result or replacing professional advice.'], ['Support contact', 'Give qualified prospects a clear, privacy-conscious way to begin.']],
    cases: [['KYPCL', 'kypcl.html']]
  },
  {
    slug: 'real-estate', name: 'Real Estate', label: 'Real Estate & Property', image: 'real-estate.png',
    imageAlt: 'Real estate advisor showing a residential property to prospective buyers',
    hero: 'Connect people to the right property conversation.',
    intro: 'Buyers, sellers, tenants, and property owners arrive with different questions and timelines. We create a clearer digital path through services, neighborhoods, property information, proof, and a useful inquiry or showing request.',
    audience: 'buyers, sellers, renters, and property owners comparing local expertise',
    choice: 'accurate property or service information, local context, team credibility, and a responsive inquiry path',
    action: 'qualified property and service inquiries',
    local: 'actual markets served, listing availability, brokerage services, and property types',
    secondTitle: 'Property Management SEO', secondSlug: 'property-management-seo', secondFocus: 'Give owners and tenants separate, useful paths, with clear services, property types, service areas, and contact expectations.',
    profileFocus: 'Keep eligible offices and business categories accurate; distinguish a real office from the neighborhoods or buildings a team serves.',
    ppcTitle: 'PPC for Real Estate', ppcFocus: 'Separate seller, buyer, rental, and property-management intent so budgets and landing pages match the audience.',
    reputationFocus: 'Use genuine client feedback to explain responsiveness and service, while avoiding promises about property value or transaction outcomes.',
    designFocus: 'Make listings or service paths, neighborhoods, team information, and inquiry forms coherent on mobile and desktop.',
    process: [['Separate audiences', 'Give buyers, sellers, tenants, and owners paths that reflect different decisions.'], ['Show relevant context', 'Use accurate listings, services, market coverage, and team proof.'], ['Make the next step clear', 'Connect showings and consultations to realistic follow-up.']],
    cases: []
  },
  {
    slug: 'retail-ecommerce', name: 'Retail & eCommerce', label: 'Retail & eCommerce', image: 'retail-ecommerce.png',
    imageAlt: 'Independent retailer packing an online order inside a neighborhood shop',
    hero: 'Make discovery and buying feel like one connected experience.',
    intro: 'Shoppers compare products, delivery, return policies, trust, and price across devices and channels. We organize the storefront and marketing around product discovery, useful information, and a smoother path to purchase.',
    audience: 'shoppers comparing products, local stores, and online purchasing options',
    choice: 'clear product details, availability, delivery and return information, customer proof, and a usable checkout',
    action: 'qualified store visits and completed purchases',
    local: 'store locations, inventory availability, delivery coverage, and online-only versus in-store operations',
    secondTitle: 'eCommerce SEO', secondSlug: 'ecommerce-seo', secondFocus: 'Improve category and product discovery with useful descriptions, sensible site architecture, and technical handling of variants and availability.',
    profileFocus: 'Google Business Profile work applies to eligible physical retail locations; an online-only store should not be presented as a storefront it does not have.',
    ppcTitle: 'PPC for Retail', ppcFocus: 'Connect product or category intent with inventory, margins, landing pages, and the post-click shopping experience.',
    reputationFocus: 'Use real customer feedback to identify product and fulfillment questions, and respond clearly to service issues.',
    designFocus: 'Make categories, product details, stock, delivery, returns, and checkout easy to understand and use across devices.',
    process: [['Organize discovery', 'Help shoppers browse by need, category, and product detail.'], ['Reduce uncertainty', 'Show availability, fulfillment, returns, and authentic product proof.'], ['Complete the path', 'Connect marketing traffic to a usable purchase or store-visit experience.']],
    cases: [['Coin & Jewelry Gallery', 'coin-jewelry-gallery-boca-raton.html']]
  }
];
